language: java

install:
  - pip install http://dev.jandy.org/jandy-python.zip
  - mvn -DskipTests=true install
  - mvn -Dmdep.outputFile=dep.txt dependency:build-classpath

script:
  - mvn test
  - travis_wait 30 jandy

notifications:
  - email: false
